# sets value
# - ${EASTL_DEFINITIONS} - use it like "ADD_DEFINITIONS(${EASTL_DEFINITIONS})"
# - ${EASTL_INCLUDE_DIR} - use it like INCLUDE_DIRECTORIES(${EASTL_INCLUDE_DIR})"
# - ${EASTL_LIBRARY}     - use it like "TARGET_LINK_LIBRARIES(${TARGET} ${EASTL_LIBRARY})"
# - ${EASTL_LIBRARY_DIR} - use it like "LINK_DIRECTORIES(${EASTL_LIBRARY_DIR})"


IF(!${EASTL_PATH})
	SET(${EASTL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/EASTL")
ENDIF()

# set warning flags
IF((${CMAKE_CXX_COMPILER_ID} MATCHES "GNU") OR (${CMAKE_CXX_COMPILER_ID} MATCHES "Clang"))
	SET(EASTL_DEFINITIONS "-Wall -Wextra -Werror")
ENDIF()

SET(EASTL_INCLUDE_DIR "${EASTL_PATH}/include")
SET(EASTL_LIBRARY "EASTL")
SET(EASTL_LIBRARY_DIR "${EASTL_PATH}")
