# sets value
# - ${EASTL_DEFINITIONS} - use it like "ADD_DEFINITIONS(${EASTL_DEFINITIONS})"
# - ${EASTL_INCLUDE_DIR} - use it like INCLUDE_DIRECTORIES(${EASTL_INCLUDE_DIR})"
# - ${EASTL_LIBRARY}     - use it like "TARGET_LINK_LIBRARIES(${TARGET} ${EASTL_LIBRARY})"
# - ${EASTL_LIBRARY_DIR} - use it like "LINK_DIRECTORIES(${EASTL_LIBRARY_DIR})"

IF(NOT DEFINED EASTL_PATH)
	SET(EASTL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/EASTL")
ENDIF()

# set warning flags
IF((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
	SET(EASTL_DEFINITIONS "-Wall -Wextra -Werror")
ENDIF()
IF(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	LIST(APPEND EASTL_DEFINITIONS "-D EASTL_VA_COPY_ENABLED=0")
ENDIF()
IF(CMAKE_BUILD_TYPE MATCHES "Debug")
	LIST(APPEND EASTL_DEFINITIONS "-D _DEBUG" "-D EA_DEBUG")
ENDIF()

SET(EASTL_INCLUDE_DIR "${EASTL_PATH}/include")
SET(EASTL_LIBRARY "EASTL")
SET(EASTL_LIBRARY_DIR "${EASTL_PATH}/lib")

IF($ENV{CXX} MATCHES "-std=c\\+\\+0x")
	LIST(APPEND EASTL_DEFINITIONS "-D EA_COMPILER_IS_CPLUSPLUS_0X")
ENDIF()
