# sets value
# - ${EASTL_LIBRARIES} - use it like "TARGET_LINK_LIBRARIES(${TARGET} ${EASTL_LIBRARIES})"

FUNCTION(FIND_EASTL EASTL_PATH)
	# set warning flags
	IF((${CMAKE_CXX_COMPILER_ID} MATCHES "GNU") OR (${CMAKE_CXX_COMPILER_ID} MATCHES "Clang"))
		SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror")
	ENDIF()

	INCLUDE_DIRECTORIES(${EASTL_PATH}/include)
	LINK_DIRECTORIES(${EASTL_PATH})

	SET(EASTL_LIBRARIES EASTL)
ENDFUNCTION()
